### PR TITLE
Feature #12809 and Bug #13833 - #7 continuation

### PR DESCRIPTION
**Pull request by 650elx**
Continuation of the #7  - please reference to previous discussion.

### CODE REVIEW

**Comment by jordanhubbard** [comment]
I'm not sensing a unifying theme here.  The cow was there for @surajrav, who worships them and got a spiritual lift from being one in the CLI every time.  The dinosaur connotes... I am not sure what it connotes.  Oil consumption?  The House of Saud?   I don't see a direct connection.

If we're going to change the animals around to please more people than just @surajrav and anyone else with similarly fond cow-centric thoughts, perhaps we should simply follow the Chinese zodiac and present the appropriate animal each year.  This year is the year of the Monkey.  There aren't a lot of ASCII monkeys on the internet to choose from, but the number is also non-zero.   Just a suggestion.  Like I said, I'm not sure what the unifying theme is and there should be some underlying reason for presenting any ascii art at launch time, or we're not really thinking like engineers.

**Comment by 650elx** [comment]
Jordan,

Oh....I see...
Dinosaur with a hat felt just right for me...I didn't expect the spanish inquisition though !

I will follow the spiritual journey of the 2016  holy Monkey.
I'm going to pursuit this path for finding the true Meaning of Life, and a proper ascii animal pattern for FN10.

But I need time for that  - that's a serious task for sure.

**Comment by jpaetzel** [comment]
No one ever expects the Spanish Inquisition.

**Comment by 650elx** [comment]
No need for this to be a pull request anymore -  Monkey is finished and I fix other issues as regular commits.

**Pull request closed without merging**
