### PR TITLE
Bug #15716

### PR DESCRIPTION
**Pull request by 650elx**
UserUpdateTask needs this modification too - I will make it later.

### CODE REVIEW

**Comment by 650elx** [comment]
UserUpdateTask changed. I've copied the logic(imho should be changed) and move validation to verify().
I've tested it on 2 week old FN10 build with some dependencies fixed - lastest builds seems to have some flaws.

**Comment by jceel** [comment]
verify() code can't make any assumptions on the current system state (eg. existence of the volume) because of the tasks queueing. it can only validate directly passed parameters (eg. using a regex).

**Comment by 650elx** [comment]
Yes - I was thinking about that. I will change that when the new builds become more stable.
Do you intrested in changing plugin logic in some places  ?

**Comment by 650elx** [comment]
I've modified UserCreate and UserUpdate tasks so the /mnt directory is no logner valid for a user defined home directory. If you would like to receive further modifications please write a comment on my concerns in bug tracking system.

I've tested this modifications on a build described as 2016-06-11

**Pull request merged**
