### PR TITLE
Feature #12809 and Bug #13833 + dinosaur and cow

### PR DESCRIPTION
**Pull request by 650elx**
Dinosaur on ssh login and cow-operation while leaving cli - tell me if you like it.

### CODE REVIEW

**Comment by jordanhubbard** [comment]
O_O   That's... an interesting pull request...  Words fail me at the moment.. :)

**Comment by 650elx** [comment]
:D IMHO. Decent commit description should be short and  meaningful ;)

**Comment by 650elx** [comment]
Hi,

Is there anything wrong with the content of this pull request ?
We can discuss different cows and pick the right one for FN10.
On the other hand maybe the sheer message without ascii art is the most convenient?

Btw. Making cli cow static (the message is hardcoded anyway) we can save up to 100ms of the cli startup time...yeah...I've tested it ;)

**Comment by surajrav** [comment]
Sorry have not gotten around to checking this. I will try this week.
Can we resolve the conflicts first though?

**Comment by 650elx** [comment]
Sure - I'm going to close this pull request and later on I will open a new one.
It looks like cli is in separate repo now.

**Pull request closed without merging**
