### PR TITLE
bug15703 vm console escape sequence

### PR DESCRIPTION
**Pull request by abwaters**
Added code to support vm.console_interrupt sequence as a configurable variable.

### CODE REVIEW

**Comment by jordanhubbard** [comment]
A couple of comments:
+ bch = bytes(ch,'utf-8')[0]
Is this even necessary?  You already have a character, and you're doing a literal comparison.

 +                elif esidx > 0:
 +                    # reset stack pointer...no match
 +                    # BW: possibly write out characters up to this point if sequence not matched?

Writing out the accumulated characters is an interesting question.  On the one hand, if you eat every character in the sequence leading up to a *possible* sequence and then throw those characters away in the !match case, then you have data loss.  On the other hand, most similar systems have a notion of "prefix doubling" to spit out a prefix character.  That is to say, tmux treats ^B^B as ^B (you've "escaped" the ^B), ssh treats "~~" as "~" so that you don't lose ~ entirely (which is pretty useful in nested ssh sessions where you need to close an "inner" session).  Obviously, in this case, simply dumping the accumulated buffer wouldn't work either, because ~~ in the presence of a sequence of ~. would emit two ~'s.  Hmmmm..  We need to think about this!

**Comment by abwaters** [comment]
In python its not a literal comparison...the type conversion is 
necessary. If there is a shortcut to avoid that I would be interested 
but I didn't find one.  The use of "bytes" convert from a char to a byte 
is a python3 thing also...new for me so any feedback would be 
appreciated...err...maybe I could go the other way and create a char 
array for the comparison.  Let me research...

On the accumulated characters question...the argument i keep coming back 
to is the poor choice of sequence argument.  If the characters can be 
used up to a certain point as part of a longer string that the vm would 
want, then the escape sequence wasn't very well considered.

I can add the doubling if you like but that kills any sequences such as 
^G^G^A...right?

**Comment by jceel** [comment]
ncurses library is a bit brain-dead in Python 3 - returns strings instead of byte arrays. I think you could probably completely skip encoding/decoding from/to bytes because you're operating on ascii strings anyways.

**Comment by jceel** [comment]
Err, sorry. I misread the diff - that code is reading from stdin directly now. But the point remains - stdin is opened in character mode, so there's no need to convert to byte array and back to string.

**Comment by abwaters** [comment]
i'm using the runtime to convert the octal sequences...at a minimum i still need to do that but I can do that in advance...let me take another pass at simplifying that part...

**Pull request merged**
